Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Enable GUI
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  # Create a synced folder
  config.vm.synced_folder "src/", "/home/vagrant/src"

  # Install development environment prerequisites
  config.vm.provision :shell, path: "bootstrap.sh"

# Network
  config.vm.network "private_network", ip: "192.168.50.10"
  # HAProxy
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # Web App
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  # Redis
  config.vm.network "forwarded_port", guest: 6379, host: 6379
  # RabbitMQ
  config.vm.network "forwarded_port", guest: 15672, host: 15672
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  # PostgreSQL
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  # Elasticsearch
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  # Kibana
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  # Flower
  config.vm.network "forwarded_port", guest: 5555, host: 5555
end
